quiz2_redo/config/routes.rb
Rails.application.routes.draw do
  get '/support_requests/update/:id' => 'support_requests#index', as: :update_support_request
  post "/support_requests/:search" => "support_requests#index", as: :search_support_request

  resources :support_requests

  root 'support_requests#index'

end

quiz2_redo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

quiz2_redo/app/models/name.rb
class Name < ApplicationRecord
end

quiz2_redo/app/models/support_request.rb
class SupportRequest < ApplicationRecord
  paginates_per 7

  validates :name, presence: true
  validates :email, presence: true

  after_initialize :set_status_default

  def set_status_default
    self.status ||= false
  end

  def self.search(query)
    if (query)
      where(["name LIKE ? OR email LIKE ? OR department LIKE ? OR message LIKE ? ", "%#{query}", "%#{query}", "%#{query}", "%#{query}"])
    else
      all
    end
  end

end

quiz2_redo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

quiz2_redo/app/controllers/support_requests_controller.rb
class SupportRequestsController < ApplicationController

  before_action :find_request, only: [:edit, :update, :destroy]

  def new
    @support_request = SupportRequest.new
  end

  def create
    support_request_params = params.require(:support_request).permit(:name, :email, :department, :message, :status)
    @support_request = SupportRequest.new support_request_params
    if @support_request.save
      flash[:notice] = "Support request created!"
      redirect_to support_requests_path(@support_request)
    else
      render (:new)
    end
  end

  def show
    @support_request = SupportRequest.find params[:id]
  end

  def index
    @support_requests = SupportRequest.all
    if params[:search_item]
       @search_item = params[:search_item]
       @support_requests = SupportRequest.where(["name ILIKE ? OR email ILIKE ? OR department ILIKE ? OR message ILIKE ?", "%#{@search_item}%","%#{@search_item}%","%#{@search_item}%","%#{@search_item}%"]).page(params[:page])
     else
       @support_requests = SupportRequest.order("id DESC").page(params[:page])
     end

     if params[:id].to_i > 0
       @support_request = SupportRequest.find params[:id]
       @support_request.status == false ? @support_request.status = true : @support_request.status = false
       @support_request.save
    end

  end

  def edit
    @support_request = SupportRequest.find params[:id]
  end

  def update
    support_request_params = params.require(:support_request).permit(:name, :email, :department, :message, :status)
    @support_request       = SupportRequest.find params[:id]
    if @support_request.update support_request_params
      redirect_to support_request_path(@support_request)
    else
      render :edit
    end
  end

  def destroy
    support_request = SupportRequest.find params[:id]
    support_request.destroy
    redirect_to support_requests_path
    flash[:alert] = "Support Request deleted!"
  end

  private

  def find_request
    @support_request = SupportRequest.find params[:id]
  end



end

quiz2_redo/app/helpers/application_helper.rb
module ApplicationHelper
end

quiz2_redo/app/helpers/support_requests_helper.rb
module SupportRequestsHelper
end

quiz2_redo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz 2 Redo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-inverse" style = 'width: 100%; background-color: #111111;'>
      <div class="container-fluid">
        <ul class="nav navbar-nav">
          <li><%= link_to "All Support Requests", root_path %></li>
          <li><%= link_to "New Support Requests", new_support_request_path  %></li>
        </ul>
      </div>
  </nav>

  </head>

  <body>


  </head>

  <body>

  </head>

  <body>

  </head>

  <body>

    <%= yield %>
  </body>
</html>

quiz2_redo/app/views/support_requests/_form.html.erb
<% if @support_request.errors.any? %>
  <ul>
    <% @support_request.errors.full_message.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <%= form_for @support_request do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div>
    <%= f.label :email %>
    <%= f.text_area :email %>
  </div>

  <div>
    <%= f.label :department, "Department" %>
    <%= f.radio_button :department, "Sales" %>
    <%= f.label:dep_sales, "Sales" %>
    <%= f.radio_button :department, "Marketing" %>
    <%= f.label :dept_marketing, "Marketing" %>
    <%= f.radio_button :department, "Technical" %>
    <%= f.label :dept_technical, "Technical" %>
  </div>

  <div>
    <%= f.label :message %></br>
    <%= f.text_area :message %>
  </div>
  <%= f.submit %>
  <% end %>
</div>

quiz2_redo/app/views/support_requests/edit.html.erb
<h1>Edit a Support Request </h1>
  <%= render "form" %>

quiz2_redo/app/views/support_requests/index.html.erb
<div class="container">
  <h1>All Support Requests</h1>

  <%= form_tag search_support_request_path(:search) do %>
   <%= text_area_tag :search_item %>
   <%= submit_tag "Search" %>
  <% end %>


  <table class="table table-striped">
    <thead>
      <th>Name</th>
      <th>Email</th>
      <th>Department</th>
      <th>Message</th>
    </thead>

    <tbody>
      <% @support_requests.each do |x| %>
        <tr>
          <td><%= x.name %></td>
          <td><%= x.email %></td>
          <td><%= x.department %></td>
          <td><%= x.message %></td>
          <td>
            <%= link_to "View", support_request_path(x) %>
            <%= link_to "Edit", edit_support_request_path(x) %>
            <%= link_to "Delete", support_request_path(x), method: :delete, data: {confirm: "Are you sure you want to delete this support request?"} %>
            <% if x.status == false %>
              <%= link_to "Not Done", update_support_request_path(x), class: "btn not-done"%>
            <% else %>
              <%= link_to "Done", update_support_request_path(x), class: "btn done" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
</table>


</div>


<%= paginate @support_requests %>

quiz2_redo/app/views/support_requests/new.html.erb
<div class="container">
  <h1>Supporter</h1>
  <hr>

  <%= render "form" %>

</div>

quiz2_redo/app/views/support_requests/show.html.erb
<div class="container">
  <h2>View Support Request</h2>

  <p><strong>Name:</strong> <%= @support_request.name %><br>
     <strong>Email:</strong> <%= @support_request.email %><br>
     <strong>Department:</strong> <%= @support_request.department %>
  </p>
  <p><strong>Message:</strong> <%= @support_request.message %></p>
</div>